### ISSUE TITLE
引脚连接

### ISSUE THREAD

**Issue by Needrom** [Mfweb/ESP32-WIFI-Camera#3]
想问一下，控制数据采集只用连25 26引脚吗  好像没有看到其他引脚配置

**Comment by Mfweb** [comment]
25 26是SCCB引脚，类似于I2C

FIFO引脚详细查看  https://github.com/Mfweb/ESP32-WIFI-Camera/blob/b515c75dcd9c021def5a16e195f6a8b4700cce6e/main/ov7725.c#L153

**Comment by Needrom** [comment]
好的，谢谢大佬
